# Generated by Django 5.1.2 on 2024-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='complete_at',
            field=models.DateField(blank=True, null=True, verbose_name='Complete Date'),
        ),
    ]
