# Generated by Django 5.1.2 on 2024-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_complete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='number_of_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Sales'),
        ),
    ]
