# Generated by Django 5.1.2 on 2024-10-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('full_stack_developer', 'Full Stack Developer'), ('test_engineer', 'Test Engineer'), ('data_analyst', 'Data Analyst'), ('data_scientist', 'Data Scientist'), ('system_administrator', 'System Administrator'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('ux_designer', 'UX Designer'), ('ui_designer', 'UI Designer'), ('devops_engineer', 'DevOps Engineer'), ('solutions_architect', 'Solutions Architect'), ('cybersecurity_specialist', 'Cybersecurity Specialist'), ('technical_support', 'Technical Support'), ('customer_representative', 'Customer Representative')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Daphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('jobs', models.ManyToManyField(to='daphne.job', verbose_name='Job Titles')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('daphne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daphne.daphe')),
            ],
        ),
    ]
